// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: models.sql

package models

import (
	"context"
)

const Healthcheck = `-- name: Healthcheck :exec
SELECT true
`

func (q *Queries) Healthcheck(ctx context.Context, db DBTX) error {
	_, err := db.Exec(ctx, Healthcheck)
	return err
}
