// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID   pgtype.UUID `db:"id"`
	Name string      `db:"name"`
}

type CategoryFamily struct {
	CategoryID pgtype.UUID `db:"category_id"`
	FamilyID   pgtype.UUID `db:"family_id"`
}

type CategoryItem struct {
	CategoryID pgtype.UUID `db:"category_id"`
	ItemID     pgtype.UUID `db:"item_id"`
}

type Family struct {
	ID   pgtype.UUID `db:"id"`
	Name string      `db:"name"`
}

type FamilyUser struct {
	UserID   int64       `db:"user_id"`
	FamilyID pgtype.UUID `db:"family_id"`
}

type Item struct {
	ID   pgtype.UUID `db:"id"`
	Name pgtype.Text `db:"name"`
	Link pgtype.Text `db:"link"`
}

type TgUser struct {
	TgID           int64       `db:"tg_id"`
	AccountName    string      `db:"account_name"`
	FullName       string      `db:"full_name"`
	ChosenFamilyID pgtype.UUID `db:"chosen_family_id"`
}
